### PR TITLE
Fix response with multiple examples

### LINKED ISSUE #182: Wrong style when a response can have multiple examples
When a response can have multiple examples, then : 

- The select can be empty
- The style doesn't respect the css variable

See:

Screenshot

### PR DESCRIPTION
**Pull request by j3rem1e**
Fix #182 

Screenshot

### CODE REVIEW

File: src/components/api-response.js [hunk 1]
```diff
@@ -285,7 +285,7 @@ export default class ApiResponse extends LitElement {
           <span class = 'example-panel generic-tree ${this.renderStyle === 'read' ? 'border pad-8-16' : 'border-top pad-top-8'}'>
             <select aria-label='response body example' @change='${(e) => this.onSelectExample(e)}'>
               ${mimeRespDetails.examples.map((v) => html`<option value="${v.exampleId}" ?selected=${v.exampleId === mimeRespDetails.selectedExample} > 
-                ${v.exampleSummary.length > 80 ? v.exampleId : v.exampleSummary} 
+                ${v.exampleSummary.length > 80 || v.exampleSummary.length === 0 ? v.exampleId : v.exampleSummary}
```
Comment (wparad) [inline src/components/api-response.js:288]:
```suggestion
                ${!v.exampleSummary || v.exampleSummary.length > 80 ? v.exampleId : v.exampleSummary} 
```

**Review by wparad — APPROVED** [review]

**Comment by wparad** [comment]
Thank you. As soon as the merge build runs this fix will be released in the 1.1 branch.
